"""Educational inventory of the artifacts of a request generated by opencode.

Implementation detail of ``OpencodeRuntime.extract_artifacts``. The *mechanics*
(weighing images, correlating tool_use→tool_result) are the same as Claude Code
— the wire is identical, Anthropic Messages API format — but the *markers* with
which opencode injects the instructions into the context are different and live
in a different place, so this module is standalone (no import from
``claude_code_artifacts``) so as not to couple the two runtimes.

Differences from Claude Code:
- opencode injects the instruction files (AGENTS.md/CLAUDE.md) as blocks of the
  **system prompt**, each with the literal prefix ``Instructions from: <path>``
  (Claude Code puts them in the system-reminder of the first user message as
  ``Contents of <path>``);
- there is no billing header in the system, no ``@file`` eager-loading
  (``role:"system"`` "Called the … tool"), no ``[Image: source:]`` markers;
- the file tools have lowercase names (``read``) and the path is in the
  ``filePath`` field.
"""

from __future__ import annotations

import json
import re
from typing import Any

# opencode prepends this prefix to every instruction file, one line per file,
# inside the system prompt (session/instruction.py, system() function).
_INSTRUCTIONS_RE = re.compile(r"^Instructions from: (\S+)", re.MULTILINE)

# The system observed on the wire (opencode 1.18) is ONE single block: base
# prompt, then the instruction files ("Instructions from: <path>\n<content>"),
# then other sections (skills, mcp, references) concatenated WITHOUT a closing
# delimiter for the instructions. A file's content may contain blank lines, so a
# file's span ends at the next instructions marker OR at the first opening of a
# known section. Openings verified against the opencode 1.18 bundle (SystemPrompt
# .skills/.mcp, ReferenceGuidance): fragile by construction, to be re-verified at
# every opencode major.
_SECTION_OPENERS_RE = re.compile(
    r"^(?:Skills provide specialized instructions"
    r"|<mcp_instructions>"
    r"|Project references provide additional directories"
    r"|<available_references>)",
    re.MULTILINE,
)

# Tools whose tool_result injects into the context the *content of a file*.
_FILE_READ_TOOLS = {"read"}
# Field of the `read` tool schema carrying the path (opencode uses camelCase
# ``filePath``; variants are accepted for robustness to version differences).
_READ_PATH_KEYS = ("filePath", "file_path", "path")


def _jsize(obj: Any) -> int:
    try:
        return len(json.dumps(obj, ensure_ascii=False))
    except (TypeError, ValueError):
        return len(str(obj))


def _block_text(block: Any) -> str:
    if isinstance(block, str):
        return block
    if isinstance(block, dict) and block.get("type") == "text":
        return block.get("text") or ""
    return ""


def _message_blocks(msg: Any) -> list[Any]:
    if not isinstance(msg, dict):
        return []
    content = msg.get("content")
    if isinstance(content, str):
        return [{"type": "text", "text": content}]
    return content if isinstance(content, list) else []


def _has_tool_result(blocks: list[Any]) -> bool:
    return any(isinstance(b, dict) and b.get("type") == "tool_result" for b in blocks)


def _image_weight(block: dict[str, Any]) -> int:
    data = (block.get("source") or {}).get("data") or ""
    return len(data) if isinstance(data, str) else _jsize(data)


def _content_len(content: Any) -> int:
    if isinstance(content, str):
        return len(content)
    if isinstance(content, list):
        total = 0
        for b in content:
            if isinstance(b, dict) and b.get("type") == "image":
                total += _image_weight(b)
            else:
                total += len(_block_text(b))
        return total
    return _jsize(content)


def _instruction_label(path: str) -> tuple[str, str]:
    """(kind, label) for an instruction file injected by opencode.

    The generic kind ``claude-md`` (project/global instructions) already
    rendered by the frontend is reused; the label is the file name, which tells
    AGENTS.md from CLAUDE.md."""
    return "claude-md", path.rsplit("/", 1)[-1]


def _instruction_spans(text: str) -> list[tuple[str, int, int]]:
    """``(path, start, end)`` spans of the instruction files inside a system text.

    ``end`` is the minimum between the next ``Instructions from:`` marker and
    the first opening of a known section (see ``_SECTION_OPENERS_RE``): a file's
    content may contain blank lines, so one cannot stop at the first blank
    line."""
    matches = list(_INSTRUCTIONS_RE.finditer(text))
    spans: list[tuple[str, int, int]] = []
    for i, m in enumerate(matches):
        hard_end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        boundary = _SECTION_OPENERS_RE.search(text, m.end(), hard_end)
        spans.append((m.group(1), m.start(), boundary.start() if boundary else hard_end))
    return spans


def _split_system_text(
    text: str, by_path: dict[str, dict[str, Any]], order: list[dict[str, Any]]
) -> int:
    """Separates the instruction files from a system text; returns the leftover chars.

    The artifacts flow into ``by_path``/``order`` (shared across several
    blocks): repeated reads of the same path sum their weights into a single
    artifact instead of duplicating it."""
    instr_chars = 0
    for path, start, end in _instruction_spans(text):
        span = end - start
        instr_chars += span
        art = by_path.get(path)
        if art is None:
            kind, label = _instruction_label(path)
            art = {"kind": kind, "label": label, "path": path, "chars": 0}
            by_path[path] = art
            order.append(art)
        art["chars"] += span
    return len(text) - instr_chars


def _extract_system_and_instructions(system: Any) -> list[dict[str, Any]]:
    """System prompt + instruction files separated out, in a NON additive way.

    The weight of the ``Instructions from:`` spans is subtracted from the system
    prompt total and attributed to one artifact per file: this way the sum of
    the chips reflects the real composition of the context, without double
    counting.

    This holds both for a **string** system and for a **list** of blocks: on the
    observed wire (opencode 1.18) the system is a single block concatenating
    base prompt, instructions and following sections, so in the list case too
    every block must be split by span, not classified as a whole.
    """
    blocks: list[str]
    if isinstance(system, str):
        blocks = [system]
    elif isinstance(system, list):
        blocks = [_block_text(b) for b in system]
    else:
        return []

    system_chars = 0
    by_path: dict[str, dict[str, Any]] = {}
    order: list[dict[str, Any]] = []
    for text in blocks:
        system_chars += _split_system_text(text, by_path, order)

    result: list[dict[str, Any]] = []
    if system_chars > 0:
        result.append({"kind": "system", "label": "System prompt", "chars": system_chars})
    result.extend(order)
    return result


def _extract_images(messages: list[Any]) -> list[dict[str, Any]]:
    """One artifact per image pasted by the user.

    As in Claude Code, images sibling to a ``tool_result`` are tool output
    (content of a file read) and must weigh on the ``read-file``, not here: only
    messages without a tool_result are considered. opencode does not add markers
    with the source path, so the label is generic."""
    artifacts: list[dict[str, Any]] = []
    for msg in messages:
        blocks = _message_blocks(msg)
        if not blocks or _has_tool_result(blocks):
            continue
        for block in blocks:
            if not isinstance(block, dict) or block.get("type") != "image":
                continue
            artifacts.append(
                {
                    "kind": "image",
                    "label": "Image",
                    "path": None,
                    "media_type": (block.get("source") or {}).get("media_type"),
                    "chars": _image_weight(block),
                }
            )
    return artifacts


def _read_path(tool_input: Any) -> str | None:
    if not isinstance(tool_input, dict):
        return None
    for key in _READ_PATH_KEYS:
        v = tool_input.get(key)
        if isinstance(v, str) and v:
            return v
    return None


def _extract_read_files(messages: list[Any]) -> list[dict[str, Any]]:
    """Files loaded into the context by a ``read`` decided by the LLM.

    Correlates ``tool_result.tool_use_id → tool_use.input`` to get back to the
    path; repeated reads of the same file flow into one artifact with summed
    weights. Images sibling to the tool_result (e.g. rendered pages) weigh on
    this artifact."""
    uses: dict[str, tuple[str, dict[str, Any]]] = {}
    for msg in messages:
        for block in _message_blocks(msg):
            if isinstance(block, dict) and block.get("type") == "tool_use" and block.get("id"):
                uses[block["id"]] = (block.get("name") or "", block.get("input") or {})

    artifacts: list[dict[str, Any]] = []
    by_path: dict[str, dict[str, Any]] = {}
    for msg in messages:
        if not isinstance(msg, dict) or msg.get("role") != "user":
            continue
        blocks = _message_blocks(msg)
        sibling_images = 0
        msg_artifacts: list[dict[str, Any]] = []
        for block in blocks:
            if not isinstance(block, dict):
                continue
            if block.get("type") == "image":
                sibling_images += _image_weight(block)
                continue
            if block.get("type") != "tool_result":
                continue
            name, tool_input = uses.get(block.get("tool_use_id"), ("", {}))
            if name not in _FILE_READ_TOOLS:
                continue
            file_path = _read_path(tool_input)
            if not file_path:
                continue
            chars = _content_len(block.get("content"))
            existing = by_path.get(file_path)
            if existing is None:
                existing = {
                    "kind": "read-file",
                    "label": file_path.rsplit("/", 1)[-1],
                    "path": file_path,
                    "description": f"read by the agent via {name}",
                    "chars": chars,
                }
                by_path[file_path] = existing
                artifacts.append(existing)
            else:
                existing["chars"] += chars
            msg_artifacts.append(existing)
        if sibling_images and len(msg_artifacts) == 1:
            msg_artifacts[0]["chars"] += sibling_images
    return artifacts


def _extract_tools(tools: Any) -> list[dict[str, Any]]:
    if not tools or not isinstance(tools, list):
        return []
    return [
        {
            "kind": "tools",
            "label": f"Tools ({len(tools)})",
            "count": len(tools),
            "chars": _jsize(tools),
        }
    ]


def extract_artifacts(body: Any) -> list[dict[str, Any]]:
    """Inventory of the artifacts making up the ``body`` request.

    Robust to a non-dict or partial ``body``. See the Claude Code twin in
    ``claude_code_artifacts.extract_artifacts``."""
    if not isinstance(body, dict):
        return []
    messages = body.get("messages")
    messages = messages if isinstance(messages, list) else []

    artifacts: list[dict[str, Any]] = []
    artifacts += _extract_system_and_instructions(body.get("system"))
    artifacts += _extract_images(messages)
    artifacts += _extract_read_files(messages)
    artifacts += _extract_tools(body.get("tools"))
    return artifacts
