# agentspy install script (Windows PowerShell)
#
# - writes %USERPROFILE%\.config\agentspy\hooks.json from
#   hooks\settings-example.json, pointing each hook command at this
#   checkout's real path (invoked through `python`)
# - adds a `claude-spy [tag]` PowerShell function to your profile ($PROFILE)
#
# Usage:
#   .\install.ps1              install (creates/updates hooks.json + function)
#   .\install.ps1 -NoRc        write hooks.json only, print the function instead of installing it
#   .\install.ps1 -Uninstall   remove the claude-spy function from your profile
#
# Note: this script is community-contributed and not covered by CI on
# Windows; please report issues. It assumes `python` is on PATH and that
# your PowerShell execution policy allows running local scripts (see
# `Set-ExecutionPolicy -Scope CurrentUser RemoteSigned` if `.\install.ps1`
# is refused).

[CmdletBinding()]
param(
    [switch]$NoRc,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$AgentspyDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfigDir   = Join-Path $HOME ".config\agentspy"
$HooksFile   = Join-Path $ConfigDir "hooks.json"
$HookScript  = Join-Path $AgentspyDir "hooks\agentspy_hook.py"
$ExampleFile = Join-Path $AgentspyDir "hooks\settings-example.json"

$MarkerStart = "# >>> agentspy claude-spy >>>"
$MarkerEnd   = "# <<< agentspy claude-spy <<<"

function Remove-ClaudeSpyBlock {
    param([string]$ProfilePath)
    if (-not (Test-Path $ProfilePath)) { return }
    $content = Get-Content $ProfilePath -Raw
    if ($null -eq $content -or $content -notmatch [regex]::Escape($MarkerStart)) { return }
    $pattern = "(?s)\r?\n?" + [regex]::Escape($MarkerStart) + ".*?" + [regex]::Escape($MarkerEnd) + "\r?\n?"
    $newContent = [regex]::Replace($content, $pattern, "")
    Set-Content -Path $ProfilePath -Value $newContent -NoNewline
    Write-Host "  removed claude-spy function from $ProfilePath"
}

if ($Uninstall) {
    Remove-ClaudeSpyBlock -ProfilePath $PROFILE
    Write-Host "Uninstall complete. ($HooksFile left untouched, remove it by hand if you want)"
    exit 0
}

Write-Host "agentspy install (Windows)"
Write-Host "  agentspy dir : $AgentspyDir"
Write-Host "  hooks config : $HooksFile"

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

# rebuild hooks.json from settings-example.json, pointing every hook command
# at this checkout, invoked through the `python` interpreter
$settings = Get-Content $ExampleFile -Raw | ConvertFrom-Json
foreach ($hookName in $settings.hooks.PSObject.Properties.Name) {
    foreach ($entry in $settings.hooks.$hookName) {
        foreach ($hookCmd in $entry.hooks) {
            $hookCmd.command = "python `"$HookScript`""
        }
    }
}
$settings | ConvertTo-Json -Depth 10 | Set-Content -Path $HooksFile
Write-Host "  -> wrote $HooksFile"

$FunctionBlock = @"
$MarkerStart
# generated by agentspy/install.ps1 - re-run install.ps1 to update
function claude-spy {
    param([string]`$Tag = "spy")
    `$oldApiKey  = `$env:ANTHROPIC_API_KEY
    `$oldHeaders = `$env:ANTHROPIC_CUSTOM_HEADERS
    `$oldBaseUrl = `$env:ANTHROPIC_BASE_URL
    `$oldTag     = `$env:AGENTSPY_TAG
    try {
        `$env:AGENTSPY_TAG = `$Tag
        Write-Host "AGENTSPY_TAG=`$Tag"
        `$env:ANTHROPIC_API_KEY = ""
        `$env:ANTHROPIC_CUSTOM_HEADERS = "x-agentspy-tag: `$Tag"
        `$env:ANTHROPIC_BASE_URL = "http://127.0.0.1:8082"
        claude --settings "$HooksFile"
    } finally {
        `$env:ANTHROPIC_API_KEY = `$oldApiKey
        `$env:ANTHROPIC_CUSTOM_HEADERS = `$oldHeaders
        `$env:ANTHROPIC_BASE_URL = `$oldBaseUrl
        `$env:AGENTSPY_TAG = `$oldTag
    }
}
$MarkerEnd
"@

if ($NoRc) {
    Write-Host ""
    Write-Host "Add the following to your PowerShell profile ($PROFILE):"
    Write-Host ""
    Write-Host $FunctionBlock
} else {
    if (-not (Test-Path $PROFILE)) {
        New-Item -ItemType File -Force -Path $PROFILE | Out-Null
    }
    Remove-ClaudeSpyBlock -ProfilePath $PROFILE
    Add-Content -Path $PROFILE -Value "`n$FunctionBlock`n"
    Write-Host "  added claude-spy function to $PROFILE"
}

Write-Host ""
Write-Host "Setup complete."
Write-Host ""
Write-Host "1) start the collector (Linux/macOS/WSL, needs uv):"
Write-Host "     cd $AgentspyDir/server; uv run agentspy"
Write-Host ""
Write-Host "2) open a new PowerShell (or: . `$PROFILE) and spy a session with:"
Write-Host "     claude-spy [tag]"
Write-Host ""
Write-Host "Note: hooks.json invokes 'python' - make sure it is on PATH (or edit"
Write-Host "hooks.json and replace 'python' with 'py' / your interpreter of choice)."
