#!/usr/bin/env bash
# agentspy install script (Linux/macOS)
#
# - writes ~/.config/agentspy/hooks.json from hooks/settings-example.json,
#   with /PATH/TO/agentspy replaced by this checkout's real path
# - adds a `claude-spy [tag]` shell function to ~/.bashrc / ~/.zshrc
#
# Usage:
#   ./install.sh              install (creates/updates hooks.json + shell function)
#   ./install.sh --no-rc      write hooks.json only, print the function instead of installing it
#   ./install.sh --uninstall  remove the claude-spy function from shell rc files
#   ./install.sh --help
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTSPY_DIR="$SCRIPT_DIR"
CONFIG_DIR="$HOME/.config/agentspy"
HOOKS_FILE="$CONFIG_DIR/hooks.json"
EXAMPLE_FILE="$AGENTSPY_DIR/hooks/settings-example.json"
MARKER_START="# >>> agentspy claude-spy >>>"
MARKER_END="# <<< agentspy claude-spy <<<"

NO_RC=0
UNINSTALL=0
for arg in "$@"; do
    case "$arg" in
        --no-rc) NO_RC=1 ;;
        --uninstall) UNINSTALL=1 ;;
        -h|--help)
            sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *)
            echo "unknown option: $arg (see --help)" >&2
            exit 1
            ;;
    esac
done

remove_block() {
    local rc="$1"
    [ -f "$rc" ] || return 0
    grep -qF "$MARKER_START" "$rc" 2>/dev/null || return 0
    awk -v start="$MARKER_START" -v end="$MARKER_END" '
        $0 == start {flag=1; next}
        $0 == end {flag=0; next}
        !flag
    ' "$rc" > "$rc.tmp"
    mv "$rc.tmp" "$rc"
    echo "  removed claude-spy function from $rc"
}

if [ "$UNINSTALL" -eq 1 ]; then
    remove_block "$HOME/.bashrc"
    remove_block "$HOME/.zshrc"
    echo "Uninstall complete. ($HOOKS_FILE left untouched, remove it by hand if you want)"
    exit 0
fi

echo "agentspy install"
echo "  agentspy dir : $AGENTSPY_DIR"
echo "  hooks config : $HOOKS_FILE"

chmod +x "$AGENTSPY_DIR/hooks/agentspy_hook.py"

mkdir -p "$CONFIG_DIR"
sed "s|/PATH/TO/agentspy|$AGENTSPY_DIR|g" "$EXAMPLE_FILE" > "$HOOKS_FILE"
echo "  -> wrote $HOOKS_FILE"

read -r -d '' FUNCTION_BLOCK <<EOF || true
$MARKER_START
# generated by agentspy/install.sh - re-run install.sh to update
claude-spy () {
    ( AGENTSPY_TAG=\${1:-spy}
      echo AGENTSPY_TAG=\$AGENTSPY_TAG
      export ANTHROPIC_API_KEY=""
      export ANTHROPIC_CUSTOM_HEADERS="x-agentspy-tag: \$AGENTSPY_TAG"
      export ANTHROPIC_BASE_URL=http://127.0.0.1:8082 AGENTSPY_TAG=\$AGENTSPY_TAG
      claude --settings "$HOOKS_FILE" )
}
$MARKER_END
EOF

if [ "$NO_RC" -eq 1 ]; then
    echo
    echo "Add the following to your shell rc file (~/.bashrc, ~/.zshrc, ...):"
    echo
    echo "$FUNCTION_BLOCK"
else
    # always (re)install into the rc file of the current shell, plus any
    # other rc file that already exists, for people who use more than one
    RC_FILES=()
    case "$(basename "${SHELL:-bash}")" in
        zsh) RC_FILES+=("$HOME/.zshrc") ;;
        *) RC_FILES+=("$HOME/.bashrc") ;;
    esac
    [ -f "$HOME/.bashrc" ] && [[ " ${RC_FILES[*]-} " != *" $HOME/.bashrc "* ]] && RC_FILES+=("$HOME/.bashrc")
    [ -f "$HOME/.zshrc" ] && [[ " ${RC_FILES[*]-} " != *" $HOME/.zshrc "* ]] && RC_FILES+=("$HOME/.zshrc")

    for rc in "${RC_FILES[@]}"; do
        touch "$rc"
        remove_block "$rc"
        printf '\n%s\n' "$FUNCTION_BLOCK" >> "$rc"
        echo "  added claude-spy function to $rc"
    done
fi

echo
echo "Setup complete."
echo
echo "1) start the collector:"
echo "     cd $AGENTSPY_DIR && just up"
echo
echo "2) open a new shell (or: source ~/.bashrc / ~/.zshrc) and spy a session with:"
echo "     claude-spy [tag]"
echo
echo "   e.g.: cd my-project && claude-spy my-tag"
